# Generated by Django 4.2.2 on 2023-06-30 02:55

from django.db import migrations, models
import pvp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChargedMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_id", models.CharField()),
                ("energy", models.IntegerField()),
                (
                    "move",
                    pvp.models.DataClassField(
                        dataClass=pvp.models.CMove, max_length=102400
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FastMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_id", models.CharField()),
                ("energy_gain", models.IntegerField()),
                (
                    "move",
                    pvp.models.DataClassField(
                        dataClass=pvp.models.Move, max_length=102400
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Format",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("cup", models.CharField(max_length=32)),
                ("cp", models.PositiveSmallIntegerField()),
                ("meta", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dex", models.IntegerField()),
                ("species_name", models.CharField()),
                ("species_id", models.CharField()),
                (
                    "data",
                    pvp.models.DataClassField(
                        dataClass=pvp.models.PokemonData, max_length=102400
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("species_name", models.CharField()),
                ("species_id", models.SlugField()),
                ("rating", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
