# Generated by Django 4.2.2 on 2023-07-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pvp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchup",
            name="opponent",
        ),
        migrations.RemoveField(
            model_name="matchup",
            name="pokemon",
        ),
        migrations.RemoveField(
            model_name="ranking",
            name="counters",
        ),
        migrations.RemoveField(
            model_name="ranking",
            name="matchups",
        ),
        migrations.RemoveField(
            model_name="ranking",
            name="pokemon",
        ),
        migrations.RemoveField(
            model_name="ranking",
            name="scenario",
        ),
        migrations.DeleteModel(
            name="Counter",
        ),
        migrations.DeleteModel(
            name="Matchup",
        ),
        migrations.DeleteModel(
            name="Ranking",
        ),
    ]
