# Generated by Django 4.2.2 on 2023-07-11 02:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvp", "0002_remove_matchup_opponent_remove_matchup_pokemon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chargedmove",
            name="archetype",
        ),
        migrations.RemoveField(
            model_name="fastmove",
            name="archetype",
        ),
        migrations.AddField(
            model_name="pokemon",
            name="legacy_moves",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, null=True, size=None
            ),
        ),
    ]
